### ISSUE TITLE
Try Refactoring SCSS Paths

### ISSUE THREAD

**Issue by Karvel** [Shift3/boilerplate-client-angular#305]
Yeah, the sass ones are a little different and I usually have to fiddle with it before it works. Here is an example of one I have done in the past:

`@import "~src/assets/styles/theme.scss";`

Not a guarantee it will work, but if you adjust the path to your structure I'm thinking it should work.

_Originally posted by @mwallert in https://github.com/Shift3/boilerplate-client-angular/pull/304#discussion_r606364946_

**Comment by Basim-Elayan** [comment]
I believe this issue has already been done by this PR
https://github.com/Shift3/boilerplate-client-angular/pull/349
