### ISSUE TITLE
Docker FAQ README

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/boilerplate-client-angular#353]
## Desired Use Case

We would like the most common issues specified and solutions documented. 

## Actual/Current Behavior

We would like to create an FAQ section on common docker issues and how to solve them. Preferably with a link to: https://github.com/Shift3/standards-and-practices/issues/174 to cover the most common issues.  

How to start the project: 
- `docker-compose up`
- `docker-compose down`
- `docker-compose down -v`

**Comment by michaelachrisco** [comment]
@22antonio Did you mean to reopen this? Is this finished?

**Comment by 22antonio** [comment]
I think this is done. Updates to the DockerFAQ will be done on the wiki. There's no need to keep this open
